/** 
 * NOTE: This is an edited version of the FullCalendar v1.5.4 (eventorganiser branch)
*/

/*
 FullCalendar v1.5.4
 http://arshaw.com/fullcalendar/

 Use fullcalendar.css for basic styling.
 For event drag & drop, requires jQuery UI draggable.
 For event resizing, requires jQuery UI resizable.

 Copyright (c) 2011 Adam Shaw
 Dual licensed under the MIT and GPL licenses, located in
 MIT-LICENSE.txt and GPL-LICENSE.txt respectively.

 Date: Wed Oct 31 15:56:21 2012 +0000
*/
(function(l,oa){function wb(a){l.extend(true,Ya,a)}function Yb(a,b,e){function d(k){if(E){u();o();ta();T(k)}else f()}function f(){B=b.theme?"ui":"fc";a.addClass("fc");b.isRTL&&a.addClass("fc-rtl");b.theme&&a.addClass("ui-widget");E=l("<div class='fc-content' style='position:relative'/>").prependTo(a);C=new Zb(U,b);(Q=C.render())&&a.prepend(Q);y(b.defaultView);l(window).resize(pa);t()||g()}function g(){setTimeout(function(){!n.start&&t()&&T()},0)}function m(){l(window).unbind("resize",pa);C.destroy();
E.remove();a.removeClass("fc fc-rtl ui-widget")}function j(){return i.offsetWidth!==0}function t(){return l("body")[0].offsetWidth!==0}function y(k){if(!n||k!=n.name){F++;qa();var D=n,Z;if(D){(D.beforeHide||xb)();Za(E,E.height());D.element.hide()}else Za(E,1);E.css("overflow","hidden");if(n=Y[k])n.element.show();else n=Y[k]=new Ja[k](Z=s=l("<div class='fc-view fc-view-"+k+"' style='position:absolute'/>").appendTo(E),U);D&&C.deactivateButton(D.name);C.activateButton(k);T();E.css("overflow","");D&&
Za(E,1);Z||(n.afterShow||xb)();F--}}function T(k){if(j()){F++;qa();p===oa&&u();var D=false;if(!n.start||k||r<n.start||r>=n.end){n.render(r,k||0);fa(true);D=true}else if(n.sizeDirty){n.clearEvents();fa();D=true}else if(n.eventsDirty){n.clearEvents();D=true}n.sizeDirty=false;n.eventsDirty=false;ha(D);X=a.outerWidth();C.updateTitle(n.title);k=new Date;k>=n.start&&k<n.end?C.disableButton("today"):C.enableButton("today");F--;n.trigger("viewDisplay",i)}}function R(){o();if(j()){u();fa();qa();n.clearEvents();
n.renderEvents(I);n.sizeDirty=false}}function o(){l.each(Y,function(k,D){D.sizeDirty=true})}function u(){p=b.contentHeight?b.contentHeight:b.height?b.height-(Q?Q.height():0)-Sa(E):Math.round(E.width()/Math.max(b.aspectRatio,0.5))}function fa(k){F++;n.setHeight(p,k);if(s){s.css("position","relative");s=null}n.setWidth(E.width(),k);F--}function pa(){if(!F)if(n.start){var k=++v;setTimeout(function(){if(k==v&&!F&&j())if(X!=(X=a.outerWidth())){F++;R();n.trigger("windowResize",i);F--}},200)}else g()}function ha(k){if(!b.lazyFetching||
ya(n.visStart,n.visEnd))ma();else k&&da()}function ma(){J(n.visStart,n.visEnd,b)}function na(k){I=k;da()}function ca(k){da(k)}function da(k){ta();if(j()){n.clearEvents();n.renderEvents(I,k);n.eventsDirty=false}}function ta(){l.each(Y,function(k,D){D.eventsDirty=true})}function ua(k,D,Z){n.select(k,D,Z===oa?true:Z)}function qa(){n&&n.unselect()}function V(){T(-1)}function ea(){T(1)}function ka(){hb(r,-1);T()}function ra(){hb(r,1);T()}function G(){r=new Date;T()}function q(k,D,Z){if(k instanceof Date)r=
M(k);else yb(r,k,D,Z);T()}function K(k,D,Z){k!==oa&&hb(r,k);D!==oa&&ib(r,D);Z!==oa&&ba(r,Z);T()}function c(){return M(r)}function z(){return n}function O(k,D){if(D===oa)return b[k];if(k=="height"||k=="contentHeight"||k=="aspectRatio"){b[k]=D;R()}}function N(k,D){if(b[k])return b[k].apply(D||i,Array.prototype.slice.call(arguments,2))}var U=this;U.options=b;U.render=d;U.destroy=m;U.refetchEvents=ma;U.reportEvents=na;U.reportEventChange=ca;U.rerenderEvents=da;U.changeView=y;U.select=ua;U.unselect=qa;
U.prev=V;U.next=ea;U.prevYear=ka;U.nextYear=ra;U.today=G;U.gotoDate=q;U.incrementDate=K;U.formatDate=function(k,D){return Oa(k,D,b)};U.formatDates=function(k,D,Z){return jb(k,D,Z,b)};U.getDate=c;U.getView=z;U.option=O;U.trigger=N;$b.call(U,b,e);var ya=U.isFetchNeeded,J=U.fetchEvents,i=a[0],C,Q,E,B,n,Y={},X,p,s,v=0,F=0,r=new Date,I=[],L;yb(r,b.year,b.month,b.date);b.droppable&&l(document).bind("dragstart",function(k,D){var Z=k.target,ja=l(Z);if(!ja.parents(".fc").length){var ia=b.dropAccept;if(l.isFunction(ia)?
ia.call(Z,ja):ja.is(ia)){L=Z;n.dragStart(L,k,D)}}}).bind("dragstop",function(k,D){if(L){n.dragStop(L,k,D);L=null}})}function Zb(a,b){function e(){o=b.theme?"ui":"fc";if(b.header)return R=l("<table class='fc-header' style='width:100%'/>").append(l("<tr/>").append(f("left")).append(f("center")).append(f("right")))}function d(){R.remove()}function f(u){var fa=l("<td class='fc-header-"+u+"'/>");(u=b.header[u])&&l.each(u.split(" "),function(pa){pa>0&&fa.append("<span class='fc-header-space'/>");var ha;
l.each(this.split(","),function(ma,na){if(na=="title"){fa.append("<span class='fc-header-title'><h2>&nbsp;</h2></span>");ha&&ha.addClass(o+"-corner-right");ha=null}else if(l.isFunction(b.customButtons[na])){ma=b.customButtons[na](b);fa.append(ma)}else if(b.buttonui){ma=$a(b.buttonText,na);var ca=l("<span class='fc-button fc-button-"+na+" "+o+"-state-default'>"+ma+"</span>");ca.button().appendTo(fa)}else{var da;if(a[na])da=a[na];else if(Ja[na])da=function(){ca.removeClass(o+"-state-hover");a.changeView(na)};
if(da){var ta=b.theme?$a(b.buttonIcons,na):null;ma=$a(b.buttonText,na);if(ca=l("<span class='fc-button fc-button-"+na+" "+o+"-state-default'><span class='fc-button-inner'><span class='fc-button-content'>"+(ta?"<span class='fc-icon-wrap'><span class='ui-icon ui-icon-"+ta+"'/></span>":ma)+"</span><span class='fc-button-effect'><span></span></span></span></span>")){ca.click(function(){ca.hasClass(o+"-state-disabled")||da()}).mousedown(function(){ca.not("."+o+"-state-active").not("."+o+"-state-disabled").addClass(o+
"-state-down")}).mouseup(function(){ca.removeClass(o+"-state-down")}).hover(function(){ca.not("."+o+"-state-active").not("."+o+"-state-disabled").addClass(o+"-state-hover")},function(){ca.removeClass(o+"-state-hover").removeClass(o+"-state-down")}).appendTo(fa);ha||ca.addClass(o+"-corner-left");ha=ca}}}});ha&&ha.addClass(o+"-corner-right")});return fa}function g(u){R.find("h2").html(u)}function m(u){R.find("span.fc-button-"+u).addClass(o+"-state-active")}function j(u){R.find("span.fc-button-"+u).removeClass(o+
"-state-active")}function t(u){R.find("span.fc-button-"+u).addClass(o+"-state-disabled")}function y(u){R.find("span.fc-button-"+u).removeClass(o+"-state-disabled")}var T=this;T.render=e;T.destroy=d;T.updateTitle=g;T.activateButton=m;T.deactivateButton=j;T.disableButton=t;T.enableButton=y;var R=l([]),o}function $b(a,b){function e(c,z){return!ea||c<ea||z>ka}function d(c,z,O){ea=c;ka=z;K=[];c=++ra;G=z=V.length;for(var N=0;N<z;N++)f(V[N],c,O)}function f(c,z,O){g(c,function(N){if(z==ra){if(N){for(var U=
0;U<N.length;U++){N[U].source=c;pa(N[U])}K=K.concat(N)}G--;G||ua(K)}},O)}function g(c,z){var O,N=Aa.sourceFetchers,U;for(O=0;O<N.length;O++){U=N[O](c,ea,ka,z);if(U===true)return;else if(typeof U=="object"){g(U,z,a);return}}if(O=c.events)if(l.isFunction(O)){u();O(M(ea),M(ka),function(C){z(C);fa()},a)}else l.isArray(O)?z(O):z();else if(c.url){var ya=c.success,J=c.error,i=c.complete;O=l.extend({},c.data||{});N=Ta(c.startParam,a.startParam);U=Ta(c.endParam,a.endParam);if(N)O[N]=Math.round(+ea/1E3);if(U)O[U]=
Math.round(+ka/1E3);u();l.ajax(l.extend({},ac,c,{data:O,success:function(C){C=C||[];var Q=ab(ya,this,arguments);if(l.isArray(Q))C=Q;z(C)},error:function(){ab(J,this,arguments);z()},complete:function(){ab(i,this,arguments);fa()}}))}else z()}function m(c){if(c=j(c)){G++;f(c,ra)}}function j(c){if(l.isFunction(c)||l.isArray(c))c={events:c};else if(typeof c=="string")c={url:c};if(typeof c=="object"){ha(c);V.push(c);return c}}function t(c){V=l.grep(V,function(z){return!ma(z,c)});K=l.grep(K,function(z){return!ma(z.source,
c)});ua(K)}function y(c){var z,O=K.length,N,U=ta().defaultEventEnd,ya=c.start-c._start,J=c.end?c.end-(c._end||U(c)):0;for(z=0;z<O;z++){N=K[z];if(N._id==c._id&&N!=c){N.start=new Date(+N.start+ya);N.end=c.end?N.end?new Date(+N.end+J):new Date(+U(N)+J):null;N.title=c.title;N.url=c.url;N.allDay=c.allDay;N.className=c.className;N.editable=c.editable;N.color=c.color;N.backgroudColor=c.backgroudColor;N.borderColor=c.borderColor;N.textColor=c.textColor;pa(N)}}pa(c);ua(K)}function T(c,z){pa(c);if(!c.source){if(z){qa.events.push(c);
c.source=qa}K.push(c)}ua(K)}function R(c){if(c){if(!l.isFunction(c)){var z=c+"";c=function(N){return N._id==z}}K=l.grep(K,c,true);for(O=0;O<V.length;O++)if(l.isArray(V[O].events))V[O].events=l.grep(V[O].events,c,true)}else{K=[];for(var O=0;O<V.length;O++)if(l.isArray(V[O].events))V[O].events=[]}ua(K)}function o(c){if(l.isFunction(c))return l.grep(K,c);else if(c){c+="";return l.grep(K,function(z){return z._id==c})}return K}function u(){q++||da("loading",null,true)}function fa(){--q||da("loading",null,
false)}function pa(c){var z=c.source||{},O=Ta(z.ignoreTimezone,a.ignoreTimezone);c._id=c._id||(c.id===oa?"_fc"+bc++:c.id+"");if(c.date){if(!c.start)c.start=c.date;delete c.date}c._start=M(c.start=kb(c.start,O));c.end=kb(c.end,O);if(c.end&&c.end<=c.start)c.end=null;c._end=c.end?M(c.end):null;if(c.allDay===oa)c.allDay=Ta(z.allDayDefault,a.allDayDefault);if(c.className){if(typeof c.className=="string")c.className=c.className.split(/\s+/)}else c.className=[]}function ha(c){if(c.className){if(typeof c.className==
"string")c.className=c.className.split(/\s+/)}else c.className=[];for(var z=Aa.sourceNormalizers,O=0;O<z.length;O++)z[O](c)}function ma(c,z){return c&&z&&na(c)==na(z)}function na(c){return(typeof c=="object"?c.events||c.url:"")||c}var ca=this;ca.isFetchNeeded=e;ca.fetchEvents=d;ca.addEventSource=m;ca.removeEventSource=t;ca.updateEvent=y;ca.renderEvent=T;ca.removeEvents=R;ca.clientEvents=o;ca.normalizeEvent=pa;var da=ca.trigger,ta=ca.getView,ua=ca.reportEvents,qa={events:[]},V=[qa],ea,ka,ra=0,G=0,
q=0,K=[];for(ca=0;ca<b.length;ca++)j(b[ca])}function hb(a,b,e){a.setFullYear(a.getFullYear()+b);e||Ka(a);return a}function ib(a,b,e){if(+a){b=a.getMonth()+b;var d=M(a);d.setDate(1);d.setMonth(b);a.setMonth(b);for(e||Ka(a);a.getMonth()!=d.getMonth();)a.setDate(a.getDate()+(a<d?1:-1))}return a}function ba(a,b,e){if(+a){b=a.getDate()+b;var d=M(a);d.setHours(9);d.setDate(b);a.setDate(b);e||Ka(a);lb(a,d)}return a}function lb(a,b){if(+a)for(;a.getDate()!=b.getDate();)a.setTime(+a+(a<b?1:-1)*cc)}function xa(a,
b){a.setMinutes(a.getMinutes()+b);return a}function Ka(a){a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a}function M(a,b){if(b)return Ka(new Date(+a));return new Date(+a)}function zb(){var a=0,b;do b=new Date(1970,a++,1);while(b.getHours());return b}function Fa(a,b,e){for(b=b||1;!a.getDay()||e&&a.getDay()==1||!e&&a.getDay()==6;)ba(a,b);return a}function Ca(a,b){return Math.round((M(a,true)-M(b,true))/Ab)}function yb(a,b,e,d){if(b!==oa&&b!=a.getFullYear()){a.setDate(1);
a.setMonth(0);a.setFullYear(b)}if(e!==oa&&e!=a.getMonth()){a.setDate(1);a.setMonth(e)}d!==oa&&a.setDate(d)}function kb(a,b){if(typeof a=="object")return a;if(typeof a=="number")return new Date(a*1E3);if(typeof a=="string"){if(a.match(/^\d+(\.\d+)?$/))return new Date(parseFloat(a)*1E3);if(b===oa)b=true;return Bb(a,b)||(a?new Date(a):null)}return null}function Bb(a,b){a=a.match(/^([0-9]{4})(-([0-9]{2})(-([0-9]{2})([T ]([0-9]{2}):([0-9]{2})(:([0-9]{2})(\.([0-9]+))?)?(Z|(([-+])([0-9]{2})(:?([0-9]{2}))?))?)?)?)?$/);
if(!a)return null;var e=new Date(a[1],0,1);if(b||!a[13]){b=new Date(a[1],0,1,9,0);if(a[3]){e.setMonth(a[3]-1);b.setMonth(a[3]-1)}if(a[5]){e.setDate(a[5]);b.setDate(a[5])}lb(e,b);a[7]&&e.setHours(a[7]);a[8]&&e.setMinutes(a[8]);a[10]&&e.setSeconds(a[10]);a[12]&&e.setMilliseconds(Number("0."+a[12])*1E3);lb(e,b)}else{e.setUTCFullYear(a[1],a[3]?a[3]-1:0,a[5]||1);e.setUTCHours(a[7]||0,a[8]||0,a[10]||0,a[12]?Number("0."+a[12])*1E3:0);if(a[14]){b=Number(a[16])*60+(a[18]?Number(a[18]):0);b*=a[15]=="-"?1:-1;
e=new Date(+e+b*60*1E3)}}return e}function mb(a){if(typeof a=="number")return a*60;if(typeof a=="object")return a.getHours()*60+a.getMinutes();if(a=a.match(/(\d+)(?::(\d+))?\s*(\w+)?/)){var b=parseInt(a[1],10);if(a[3]){b%=12;if(a[3].toLowerCase().charAt(0)=="p")b+=12}return b*60+(a[2]?parseInt(a[2],10):0)}}function Oa(a,b,e){return jb(a,null,b,e)}function jb(a,b,e,d){d=d||Ya;var f=a,g=b,m,j=e.length,t,y,T,R="";for(m=0;m<j;m++){t=e.charAt(m);if(t=="'")for(y=m+1;y<j;y++){if(e.charAt(y)=="'"){if(f){R+=
y==m+1?"'":e.substring(m+1,y);m=y}break}}else if(t=="(")for(y=m+1;y<j;y++){if(e.charAt(y)==")"){m=Oa(f,e.substring(m+1,y),d);if(parseInt(m.replace(/\D/,""),10))R+=m;m=y;break}}else if(t=="[")for(y=m+1;y<j;y++){if(e.charAt(y)=="]"){t=e.substring(m+1,y);m=Oa(f,t,d);if(m!=Oa(g,t,d))R+=m;m=y;break}}else if(t=="{"){f=b;g=a}else if(t=="}"){f=a;g=b}else{for(y=j;y>m;y--)if(T=dc[e.substring(m,y)]){if(f)R+=T(f,d);m=y-1;break}if(y==m)if(f)R+=t}}return R}function Ua(a){return a.end?ec(a.end,a.allDay):ba(M(a.start),
1)}function ec(a,b){a=M(a);return b||a.getHours()||a.getMinutes()?ba(a,1):Ka(a)}function fc(a,b){return(b.msLength-a.msLength)*100+(a.event.start-b.event.start)}function Cb(a,b){return a.end>b.start&&a.start<b.end}function nb(a,b,e,d){var f=[],g,m=a.length,j,t,y,T,R;for(g=0;g<m;g++){j=a[g];t=j.start;y=b[g];if(y>e&&t<d){if(t<e){t=M(e);T=false}else{t=t;T=true}if(y>d){y=M(d);R=false}else{y=y;R=true}f.push({event:j,start:t,end:y,isStart:T,isEnd:R,msLength:y-t})}}return f.sort(fc)}function ob(a){var b=
[],e,d=a.length,f,g,m,j;for(e=0;e<d;e++){f=a[e];for(g=0;;){m=false;if(b[g])for(j=0;j<b[g].length;j++)if(Cb(b[g][j],f)){m=true;break}if(m)g++;else break}if(b[g])b[g].push(f);else b[g]=[f]}return b}function Db(a,b,e){a.unbind("mouseover").mouseover(function(d){for(var f=d.target,g;f!=this;){g=f;f=f.parentNode}if((f=g._fci)!==oa){g._fci=oa;g=b[f];e(g.event,g.element,g);l(d.target).trigger(d)}d.stopPropagation()})}function Va(a,b,e){for(var d=0,f;d<a.length;d++){f=l(a[d]);f.width(Math.max(0,b-pb(f,e)))}}
function Eb(a,b,e){for(var d=0,f;d<a.length;d++){f=l(a[d]);f.height(Math.max(0,b-Sa(f,e)))}}function pb(a,b){return gc(a)+hc(a)+(b?ic(a):0)}function gc(a){return(parseFloat(l.css(a[0],"paddingLeft",true))||0)+(parseFloat(l.css(a[0],"paddingRight",true))||0)}function ic(a){return(parseFloat(l.css(a[0],"marginLeft",true))||0)+(parseFloat(l.css(a[0],"marginRight",true))||0)}function hc(a){return(parseFloat(l.css(a[0],"borderLeftWidth",true))||0)+(parseFloat(l.css(a[0],"borderRightWidth",true))||0)}function Sa(a,
b){return jc(a)+kc(a)+(b?Fb(a):0)}function jc(a){return(parseFloat(l.css(a[0],"paddingTop",true))||0)+(parseFloat(l.css(a[0],"paddingBottom",true))||0)}function Fb(a){return(parseFloat(l.css(a[0],"marginTop",true))||0)+(parseFloat(l.css(a[0],"marginBottom",true))||0)}function kc(a){return(parseFloat(l.css(a[0],"borderTopWidth",true))||0)+(parseFloat(l.css(a[0],"borderBottomWidth",true))||0)}function Za(a,b){b=typeof b=="number"?b+"px":b;a.each(function(e,d){d.style.cssText+=";min-height:"+b+";_height:"+
b})}function xb(){}function Gb(a,b){return a-b}function Hb(a){return Math.max.apply(Math,a)}function Pa(a){return(a<10?"0":"")+a}function $a(a,b){if(a[b]!==oa)return a[b];b=b.split(/(?=[A-Z])/);for(var e=b.length-1,d;e>=0;e--){d=a[b[e].toLowerCase()];if(d!==oa)return d}return a[""]}function Qa(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/'/g,"&#039;").replace(/"/g,"&quot;").replace(/\n/g,"<br />")}function Ib(a){return a.id+"/"+a.className+"/"+a.style.cssText.replace(/(^|;)\s*(top|left|width|height)\s*:[^;]*/ig,
"")}function qb(a){a.attr("unselectable","on").css("MozUserSelect","none").bind("selectstart.ui",function(){return false})}function bb(a){a.children().removeClass("fc-first fc-last").filter(":first-child").addClass("fc-first").end().filter(":last-child").addClass("fc-last")}function rb(a,b){a.each(function(e,d){d.className=d.className.replace(/^fc-\w*/,"fc-"+lc[b.getDay()])})}function Jb(a,b){var e=a.source||{},d=a.color,f=e.color,g=b("eventColor"),m=a.backgroundColor||d||e.backgroundColor||f||b("eventBackgroundColor")||
g;d=a.borderColor||d||e.borderColor||f||b("eventBorderColor")||g;a=a.textColor||e.textColor||b("eventTextColor");b=[];m&&b.push("background-color:"+m);d&&b.push("border-color:"+d);a&&b.push("color:"+a);return b.join(";")}function ab(a,b,e){if(l.isFunction(a))a=[a];if(a){var d,f;for(d=0;d<a.length;d++)f=a[d].apply(b,e)||f;return f}}function Ta(){for(var a=0;a<arguments.length;a++)if(arguments[a]!==oa)return arguments[a]}function mc(a,b){function e(j,t){if(t){ib(j,t);j.setDate(1)}j=M(j,true);j.setDate(1);
t=ib(M(j),1);var y=M(j),T=M(t),R=f("firstDay"),o=f("weekends")?0:1;if(o){Fa(y);Fa(T,-1,true)}ba(y,-((y.getDay()-Math.max(R,o)+7)%7));ba(T,(7-T.getDay()+Math.max(R,o))%7);R=Math.round((T-y)/(Ab*7));if(f("weekMode")=="fixed"){ba(T,(6-R)*7);R=6}d.title=m(j,f("titleFormat"));d.start=j;d.end=t;d.visStart=y;d.visEnd=T;g(6,R,o?5:7,true)}var d=this;d.render=e;sb.call(d,a,b,"month");var f=d.opt,g=d.renderBasic,m=b.formatDate}function nc(a,b){function e(j,t){t&&ba(j,t*7);j=ba(M(j),-((j.getDay()-f("firstDay")+
7)%7));t=ba(M(j),7);var y=M(j),T=M(t),R=f("weekends");if(!R){Fa(y);Fa(T,-1,true)}d.title=m(y,ba(M(T),-1),f("titleFormat"));d.start=j;d.end=t;d.visStart=y;d.visEnd=T;g(1,1,R?7:5,false)}var d=this;d.render=e;sb.call(d,a,b,"basicWeek");var f=d.opt,g=d.renderBasic,m=b.formatDates}function oc(a,b){function e(j,t){if(t){ba(j,t);f("weekends")||Fa(j,t<0?-1:1)}d.title=m(j,f("titleFormat"));d.start=d.visStart=M(j,true);d.end=d.visEnd=ba(M(d.start),1);g(1,1,1,false)}var d=this;d.render=e;sb.call(d,a,b,"basicDay");
var f=d.opt,g=d.renderBasic,m=b.formatDate}function sb(a,b,e){function d(w,H,S,W){v=H;F=S;f();(H=!C)?g(w,W):z();m(H)}function f(){if(k=K("isRTL")){D=-1;Z=F-1}else{D=1;Z=0}ja=K("firstDay");ia=K("weekends")?0:1;la=K("theme")?"ui":"fc";$=K("columnFormat")}function g(w,H){var S,W=la+"-widget-header",ga=la+"-widget-content",aa;S="<table class='fc-border-separate' style='width:100%' cellspacing='0'><thead><tr>";for(aa=0;aa<F;aa++)S+="<th class='fc- "+W+"'/>";S+="</tr></thead><tbody>";for(aa=0;aa<w;aa++){S+=
"<tr class='fc-week"+aa+"'>";for(W=0;W<F;W++)S+="<td class='fc- "+ga+" fc-day"+(aa*F+W)+"'><div>"+(H?"<div class='fc-day-number'/>":"")+"<div class='fc-day-content'><div style='position:relative'>&nbsp;</div></div></div></td>";S+="</tr>"}S+="</tbody></table>";w=l(S).appendTo(a);J=w.find("thead");i=J.find("th");C=w.find("tbody");Q=C.find("tr");E=C.find("td");B=E.filter(":first-child");n=Q.eq(0).find("div.fc-day-content div");bb(J.add(J.find("tr")));bb(Q);Q.eq(0).addClass("fc-first");y(E);Y=l("<div style='position:absolute;z-index:8;top:0;left:0'/>").appendTo(a)}
function m(w){var H=w||v==1,S=q.start.getMonth(),W=Ka(new Date),ga,aa,va;H&&i.each(function(wa,Ga){ga=l(Ga);aa=ea(wa);ga.html(ya(aa,$));rb(ga,aa)});E.each(function(wa,Ga){ga=l(Ga);aa=ea(wa);aa.getMonth()==S?ga.removeClass("fc-other-month"):ga.addClass("fc-other-month");+aa==+W?ga.addClass(la+"-state-highlight fc-today"):ga.removeClass(la+"-state-highlight fc-today");ga.find("div.fc-day-number").text(aa.getDate());H&&rb(ga,aa)});Q.each(function(wa,Ga){va=l(Ga);if(wa<v){va.show();wa==v-1?va.addClass("fc-last"):
va.removeClass("fc-last")}else va.hide()})}function j(w){p=w;w=p-J.height();var H,S,W;if(K("weekMode")=="variable")H=S=Math.floor(w/(v==1?2:6));else{H=Math.floor(w/v);S=w-H*(v-1)}B.each(function(ga,aa){if(ga<v){W=l(aa);Za(W.find("> div"),(ga==v-1?S:H)-Sa(W))}})}function t(w){X=w;L.clear();s=Math.floor(X/F);Va(i.slice(0,-1),s)}function y(w){w.click(T).mousedown(U)}function T(w){if(!K("selectable")){var H=parseInt(this.className.match(/fc\-day(\d+)/)[1]);H=ea(H);c("dayClick",this,H,true,w)}}function R(w,
H,S){S&&r.build();S=M(q.visStart);for(var W=ba(M(S),F),ga=0;ga<v;ga++){var aa=new Date(Math.max(S,w)),va=new Date(Math.min(W,H));if(aa<va){var wa;if(k){wa=Ca(va,S)*D+Z+1;aa=Ca(aa,S)*D+Z+1}else{wa=Ca(aa,S);aa=Ca(va,S)}y(o(ga,wa,ga,aa-1))}ba(S,7);ba(W,7)}}function o(w,H,S,W){w=r.rect(w,H,S,W,a);return O(w,a)}function u(w){return M(w)}function fa(w,H){R(w,ba(M(H),1),true)}function pa(){N()}function ha(w,H,S){var W=ua(w);c("dayClick",E[W.row*F+W.col],w,H,S)}function ma(w,H){I.start(function(S){N();S&&
o(S.row,S.col,S.row,S.col)},H)}function na(w,H,S){var W=I.stop();N();if(W){W=qa(W);c("drop",w,W,true,H,S)}}function ca(w){return M(w.start)}function da(w){return L.left(w)}function ta(w){return L.right(w)}function ua(w){return{row:Math.floor(Ca(w,q.visStart)/7),col:ka(w.getDay())}}function qa(w){return V(w.row,w.col)}function V(w,H){return ba(M(q.visStart),w*7+H*D+Z)}function ea(w){return V(Math.floor(w/F),w%F)}function ka(w){return(w-Math.max(ja,ia)+F)%F*D+Z}function ra(w){return Q.eq(w)}function G(){return{left:0,
right:X}}var q=this;q.renderBasic=d;q.setHeight=j;q.setWidth=t;q.renderDayOverlay=R;q.defaultSelectionEnd=u;q.renderSelection=fa;q.clearSelection=pa;q.reportDayClick=ha;q.dragStart=ma;q.dragStop=na;q.defaultEventEnd=ca;q.getHoverListener=function(){return I};q.colContentLeft=da;q.colContentRight=ta;q.dayOfWeekCol=ka;q.dateCell=ua;q.cellDate=qa;q.cellIsAllDay=function(){return true};q.allDayRow=ra;q.allDayBounds=G;q.getRowCnt=function(){return v};q.getColCnt=function(){return F};q.getColWidth=function(){return s};
q.getDaySegmentContainer=function(){return Y};Kb.call(q,a,b,e);Lb.call(q);Mb.call(q);pc.call(q);var K=q.opt,c=q.trigger,z=q.clearEvents,O=q.renderOverlay,N=q.clearOverlays,U=q.daySelectionMousedown,ya=b.formatDate,J,i,C,Q,E,B,n,Y,X,p,s,v,F,r,I,L,k,D,Z,ja,ia,la,$;qb(a.addClass("fc-grid"));r=new Nb(function(w,H){var S,W,ga;i.each(function(aa,va){S=l(va);W=S.offset().left;if(aa)ga[1]=W;ga=[W];H[aa]=ga});ga[1]=W+S.outerWidth();Q.each(function(aa,va){if(aa<v){S=l(va);W=S.offset().top;if(aa)ga[1]=W;ga=
[W];w[aa]=ga}});ga[1]=W+S.outerHeight()});I=new Ob(r);L=new Pb(function(w){return n.eq(w)})}function pc(){function a(V,ea){T(V);ua(e(V),ea)}function b(){R();ha().empty()}function e(V){var ea=da(),ka=ta(),ra=M(g.visStart);ka=ba(M(ra),ka);var G=l.map(V,Ua),q,K,c,z,O,N,U=[];for(q=0;q<ea;q++){K=ob(nb(V,G,ra,ka));for(c=0;c<K.length;c++){z=K[c];for(O=0;O<z.length;O++){N=z[O];N.row=q;N.level=c;U.push(N)}}ba(ra,7);ba(ka,7)}return U}function d(V,ea,ka){t(V)&&f(V,ea);ka.isEnd&&y(V)&&qa(V,ea,ka);o(V,ea)}function f(V,
ea){var ka=ma(),ra;ea.draggable({zIndex:9,delay:50,opacity:m("dragOpacity"),revertDuration:m("dragRevertDuration"),start:function(G,q){j("eventDragStart",ea,V,G,q);fa(V,ea);ka.start(function(K,c,z,O){ea.draggable("option","revert",!K||!z&&!O);ca();if(K){ra=z*7+O*(m("isRTL")?-1:1);na(ba(M(V.start),ra),ba(Ua(V),ra))}else ra=0},G,"drag")},stop:function(G,q){ka.stop();ca();j("eventDragStop",ea,V,G,q);if(ra)pa(this,V,ra,0,V.allDay,G,q);else{ea.css("filter","");u(V,ea)}}})}var g=this;g.renderEvents=a;g.compileDaySegs=
e;g.clearEvents=b;g.bindDaySeg=d;Qb.call(g);var m=g.opt,j=g.trigger,t=g.isEventDraggable,y=g.isEventResizable,T=g.reportEvents,R=g.reportEventClear,o=g.eventElementHandlers,u=g.showEvents,fa=g.hideEvents,pa=g.eventDrop,ha=g.getDaySegmentContainer,ma=g.getHoverListener,na=g.renderDayOverlay,ca=g.clearOverlays,da=g.getRowCnt,ta=g.getColCnt,ua=g.renderDaySegs,qa=g.resizableDayEvent}function qc(a,b){function e(j,t){t&&ba(j,t*7);j=ba(M(j),-((j.getDay()-f("firstDay")+7)%7));t=ba(M(j),7);var y=M(j),T=M(t),
R=f("weekends");if(!R){Fa(y);Fa(T,-1,true)}d.title=m(y,ba(M(T),-1),f("titleFormat"));d.start=j;d.end=t;d.visStart=y;d.visEnd=T;g(R?7:5)}var d=this;d.render=e;Rb.call(d,a,b,"agendaWeek");var f=d.opt,g=d.renderAgenda,m=b.formatDates}function rc(a,b){function e(j,t){if(t){ba(j,t);f("weekends")||Fa(j,t<0?-1:1)}t=M(j,true);var y=ba(M(t),1);d.title=m(j,f("titleFormat"));d.start=d.visStart=t;d.end=d.visEnd=y;g(1)}var d=this;d.render=e;Rb.call(d,a,b,"agendaDay");var f=d.opt,g=d.renderAgenda,m=b.formatDate}
function Rb(a,b,e){function d(h){Ba=h;f();v?Q():g();m()}function f(){Wa=i("theme")?"ui":"fc";Sb=i("weekends")?0:1;Tb=i("firstDay");if(Ub=i("isRTL")){Ha=-1;Ia=Ba-1}else{Ha=1;Ia=0}La=mb(i("minTime"));cb=mb(i("maxTime"));Vb=i("columnFormat")}function g(){var h=Wa+"-widget-header",P=Wa+"-widget-content",x,A,sa,za,Da,Ea=i("slotMinutes")%15==0;x="<table style='width:100%' class='fc-agenda-days fc-border-separate' cellspacing='0'><thead><tr><th class='fc-agenda-axis "+h+"'>&nbsp;</th>";for(A=0;A<Ba;A++)x+=
"<th class='fc- fc-col"+A+" "+h+"'/>";x+="<th class='fc-agenda-gutter "+h+"'>&nbsp;</th></tr></thead><tbody><tr><th class='fc-agenda-axis "+h+"'>&nbsp;</th>";for(A=0;A<Ba;A++)x+="<td class='fc- fc-col"+A+" "+P+"'><div><div class='fc-day-content'><div style='position:relative'>&nbsp;</div></div></div></td>";x+="<td class='fc-agenda-gutter "+P+"'>&nbsp;</td></tr></tbody></table>";v=l(x).appendTo(a);F=v.find("thead");r=F.find("th").slice(1,-1);I=v.find("tbody");L=I.find("td").slice(0,-1);k=L.find("div.fc-day-content div");
D=L.eq(0);Z=D.find("> div");bb(F.add(F.find("tr")));bb(I.add(I.find("tr")));aa=F.find("th:first");va=v.find(".fc-agenda-gutter");ja=l("<div style='position:absolute;z-index:2;left:0;width:100%'/>").appendTo(a);if(i("allDaySlot")){ia=l("<div style='position:absolute;z-index:8;top:0;left:0'/>").appendTo(ja);x="<table style='width:100%' class='fc-agenda-allday' cellspacing='0'><tr><th class='"+h+" fc-agenda-axis'>"+i("allDayText")+"</th><td><div class='fc-day-content'><div style='position:relative'/></div></td><th class='"+
h+" fc-agenda-gutter'>&nbsp;</th></tr></table>";la=l(x).appendTo(ja);$=la.find("tr");o($.find("td"));aa=aa.add(la.find("th:first"));va=va.add(la.find("th.fc-agenda-gutter"));ja.append("<div class='fc-agenda-divider "+h+"'><div class='fc-agenda-divider-inner'/></div>")}else ia=l([]);w=l("<div style='position:absolute;width:100%;overflow-x:hidden;overflow-y:auto'/>").appendTo(ja);H=l("<div style='position:relative;width:100%;overflow:hidden'/>").appendTo(w);S=l("<div style='position:absolute;z-index:8;top:0;left:0'/>").appendTo(H);
x="<table class='fc-agenda-slots' style='width:100%' cellspacing='0'><tbody>";sa=zb();za=xa(M(sa),cb);xa(sa,La);for(A=tb=0;sa<za;A++){Da=sa.getMinutes();x+="<tr class='fc-slot"+A+" "+(!Da?"":"fc-minor")+"'><th class='fc-agenda-axis "+h+"'>"+(!Ea||!Da?s(sa,i("axisFormat")):"&nbsp;")+"</th><td class='"+P+"'><div style='position:relative'>&nbsp;</div></td></tr>";xa(sa,i("slotMinutes"));tb++}x+="</tbody></table>";W=l(x).appendTo(H);ga=W.find("div:first");u(W.find("td"));aa=aa.add(W.find("th:first"))}
function m(){var h,P,x,A,sa=Ka(new Date);for(h=0;h<Ba;h++){A=ua(h);P=r.eq(h);P.html(s(A,Vb));x=L.eq(h);+A==+sa?x.addClass(Wa+"-state-highlight fc-today"):x.removeClass(Wa+"-state-highlight fc-today");rb(P.add(x),A)}}function j(h,P){if(h===oa)h=Wb;Wb=h;ub={};var x=I.position().top,A=w.position().top;h=Math.min(h-x,W.height()+A+1);Z.height(h-Sa(D));ja.css("top",x);w.height(h-A-1);Xa=ga.height()+1;P&&y()}function t(h){Ga=h;db.clear();Ma=0;Va(aa.width("").each(function(P,x){Ma=Math.max(Ma,l(x).outerWidth())}),
Ma);h=w[0].clientWidth;if(vb=w.width()-h){Va(va,vb);va.show().prev().removeClass("fc-last")}else va.hide().prev().addClass("fc-last");eb=Math.floor((h-Ma)/Ba);Va(r.slice(0,-1),eb)}function y(){function h(){w.scrollTop(A)}var P=zb(),x=M(P);x.setHours(i("firstHour"));var A=ea(P,x)+1;h();setTimeout(h,0)}function T(){Xb=w.scrollTop()}function R(){w.scrollTop(Xb)}function o(h){h.click(fa).mousedown(X)}function u(h){h.click(fa).mousedown(O)}function fa(h){if(!i("selectable")){var P=Math.min(Ba-1,Math.floor((h.pageX-
v.offset().left-Ma)/eb)),x=ua(P),A=this.parentNode.className.match(/fc-slot(\d+)/);if(A){A=parseInt(A[1])*i("slotMinutes");var sa=Math.floor(A/60);x.setHours(sa);x.setMinutes(A%60+La);C("dayClick",L[P],x,false,h)}else C("dayClick",L[P],x,true,h)}}function pa(h,P,x){x&&Na.build();var A=M(J.visStart);if(Ub){x=Ca(P,A)*Ha+Ia+1;h=Ca(h,A)*Ha+Ia+1}else{x=Ca(h,A);h=Ca(P,A)}x=Math.max(0,x);h=Math.min(Ba,h);x<h&&o(ha(0,x,0,h-1))}function ha(h,P,x,A){h=Na.rect(h,P,x,A,ja);return E(h,ja)}function ma(h,P){for(var x=
M(J.visStart),A=ba(M(x),1),sa=0;sa<Ba;sa++){var za=new Date(Math.max(x,h)),Da=new Date(Math.min(A,P));if(za<Da){var Ea=sa*Ha+Ia;Ea=Na.rect(0,Ea,0,Ea,H);za=ea(x,za);Da=ea(x,Da);Ea.top=za;Ea.height=Da-za;u(E(Ea,H))}ba(x,1);ba(A,1)}}function na(h){return db.left(h)}function ca(h){return db.right(h)}function da(h){return{row:Math.floor(Ca(h,J.visStart)/7),col:V(h.getDay())}}function ta(h){var P=ua(h.col);h=h.row;i("allDaySlot")&&h--;h>=0&&xa(P,La+h*i("slotMinutes"));return P}function ua(h){return ba(M(J.visStart),
h*Ha+Ia)}function qa(h){return i("allDaySlot")&&!h.row}function V(h){return(h-Math.max(Tb,Sb)+Ba)%Ba*Ha+Ia}function ea(h,P){h=M(h,true);if(P<xa(M(h),La))return 0;if(P>=xa(M(h),cb))return W.height();h=i("slotMinutes");P=P.getHours()*60+P.getMinutes()-La;var x=Math.floor(P/h),A=ub[x];if(A===oa)A=ub[x]=W.find("tr:eq("+x+") td div")[0].offsetTop;return Math.max(0,Math.round(A-1+Xa*(P%h/h)))}function ka(){return{left:Ma,right:Ga-vb}}function ra(){return $}function G(h){var P=M(h.start);if(h.allDay)return P;
return xa(P,i("defaultEventMinutes"))}function q(h,P){if(P)return M(h);return xa(M(h),i("slotMinutes"))}function K(h,P,x){if(x)i("allDaySlot")&&pa(h,ba(M(P),1),true);else c(h,P)}function c(h,P){var x=i("selectHelper");Na.build();if(x){var A=Ca(h,J.visStart)*Ha+Ia;if(A>=0&&A<Ba){A=Na.rect(0,A,0,A,H);var sa=ea(h,h),za=ea(h,P);if(za>sa){A.top=sa;A.height=za-sa;A.left+=2;A.width-=5;if(l.isFunction(x)){if(h=x(h,P)){A.position="absolute";A.zIndex=8;wa=l(h).css(A).appendTo(H)}}else{A.isStart=true;A.isEnd=
true;wa=l(p({title:"",start:h,end:P,className:["fc-select-helper"],editable:false},A));wa.css("opacity",i("dragOpacity"))}if(wa){u(wa);H.append(wa);Va(wa,A.width,true);Eb(wa,A.height,true)}}}}else ma(h,P)}function z(){B();if(wa){wa.remove();wa=null}}function O(h){if(h.which==1&&i("selectable")){Y(h);var P;Ra.start(function(x,A){z();if(x&&x.col==A.col&&!qa(x)){A=ta(A);x=ta(x);P=[A,xa(M(A),i("slotMinutes")),x,xa(M(x),i("slotMinutes"))].sort(Gb);c(P[0],P[3])}else P=null},h);l(document).one("mouseup",
function(x){Ra.stop();if(P){+P[0]==+P[1]&&N(P[0],false,x);n(P[0],P[3],false,x)}})}}function N(h,P,x){C("dayClick",L[V(h.getDay())],h,P,x)}function U(h,P){Ra.start(function(x){B();if(x)if(qa(x))ha(x.row,x.col,x.row,x.col);else{x=ta(x);var A=xa(M(x),i("defaultEventMinutes"));ma(x,A)}},P)}function ya(h,P,x){var A=Ra.stop();B();A&&C("drop",h,ta(A),qa(A),P,x)}var J=this;J.renderAgenda=d;J.setWidth=t;J.setHeight=j;J.beforeHide=T;J.afterShow=R;J.defaultEventEnd=G;J.timePosition=ea;J.dayOfWeekCol=V;J.dateCell=
da;J.cellDate=ta;J.cellIsAllDay=qa;J.allDayRow=ra;J.allDayBounds=ka;J.getHoverListener=function(){return Ra};J.colContentLeft=na;J.colContentRight=ca;J.getDaySegmentContainer=function(){return ia};J.getSlotSegmentContainer=function(){return S};J.getMinMinute=function(){return La};J.getMaxMinute=function(){return cb};J.getBodyContent=function(){return H};J.getRowCnt=function(){return 1};J.getColCnt=function(){return Ba};J.getColWidth=function(){return eb};J.getSlotHeight=function(){return Xa};J.defaultSelectionEnd=
q;J.renderDayOverlay=pa;J.renderSelection=K;J.clearSelection=z;J.reportDayClick=N;J.dragStart=U;J.dragStop=ya;Kb.call(J,a,b,e);Lb.call(J);Mb.call(J);sc.call(J);var i=J.opt,C=J.trigger,Q=J.clearEvents,E=J.renderOverlay,B=J.clearOverlays,n=J.reportSelection,Y=J.unselect,X=J.daySelectionMousedown,p=J.slotSegHtml,s=b.formatDate,v,F,r,I,L,k,D,Z,ja,ia,la,$,w,H,S,W,ga,aa,va,wa,Ga,Wb,Ma,eb,vb,Xa,Xb,Ba,tb,Na,Ra,db,ub={},Wa,Tb,Sb,Ub,Ha,Ia,La,cb,Vb;qb(a.addClass("fc-agenda"));Na=new Nb(function(h,P){function x(fb){return Math.max(Ea,
Math.min(tc,fb))}var A,sa,za;r.each(function(fb,uc){A=l(uc);sa=A.offset().left;if(fb)za[1]=sa;za=[sa];P[fb]=za});za[1]=sa+A.outerWidth();if(i("allDaySlot")){A=$;sa=A.offset().top;h[0]=[sa,sa+A.outerHeight()]}for(var Da=H.offset().top,Ea=w.offset().top,tc=Ea+w.outerHeight(),gb=0;gb<tb;gb++)h.push([x(Da+Xa*gb),x(Da+Xa*(gb+1))])});Ra=new Ob(Na);db=new Pb(function(h){return k.eq(h)})}function sc(){function a(p,s){na(p);var v,F=p.length,r=[],I=[];for(v=0;v<F;v++)p[v].allDay?r.push(p[v]):I.push(p[v]);if(u("allDaySlot")){K(e(r),
s);ta()}g(d(I),s)}function b(){ca();ua().empty();qa().empty()}function e(p){p=ob(nb(p,l.map(p,Ua),o.visStart,o.visEnd));var s,v=p.length,F,r,I,L=[];for(s=0;s<v;s++){F=p[s];for(r=0;r<F.length;r++){I=F[r];I.row=0;I.level=s;L.push(I)}}return L}function d(p){var s=z(),v=ka(),F=ea(),r=xa(M(o.visStart),v),I=l.map(p,f),L,k,D,Z,ja,ia,la=[];for(L=0;L<s;L++){k=ob(nb(p,I,r,xa(M(r),F-v)));vc(k);for(D=0;D<k.length;D++){Z=k[D];for(ja=0;ja<Z.length;ja++){ia=Z[ja];ia.col=L;ia.level=D;la.push(ia)}}ba(r,1,true)}return la}
function f(p){return p.end?M(p.end):xa(M(p.start),u("defaultEventMinutes"))}function g(p,s){var v,F=p.length,r,I,L,k,D,Z,ja,ia,la,$="",w,H,S={},W={},ga=qa(),aa;v=z();if(w=u("isRTL")){H=-1;aa=v-1}else{H=1;aa=0}for(v=0;v<F;v++){r=p[v];I=r.event;L=ra(r.start,r.start);k=ra(r.start,r.end);D=r.col;Z=r.level;ja=r.forward||0;ia=G(D*H+aa);la=q(D*H+aa)-ia;la=Math.min(la-6,la*0.95);D=Z?la/(Z+ja+1):ja?(la/(ja+1)-6)*2:la;Z=ia+la/(Z+ja+1)*Z*H+(w?la-D:0);r.top=L;r.left=Z;r.outerWidth=D;r.outerHeight=k-L;$+=m(I,
r)}ga[0].innerHTML=$;w=ga.children();for(v=0;v<F;v++){r=p[v];I=r.event;$=l(w[v]);H=fa("eventRender",I,I,$,o);if(H===false)$.remove();else{if(H&&H!==true){$.remove();$=l(H).css({position:"absolute",top:r.top,left:r.left}).appendTo(ga)}r.element=$;if(I._id===s)t(I,$,r);else $[0]._fci=v;ya(I,$)}}Db(ga,p,t);for(v=0;v<F;v++){r=p[v];if($=r.element){I=S[s=r.key=Ib($[0])];r.vsides=I===oa?(S[s]=Sa($,true)):I;I=W[s];r.hsides=I===oa?(W[s]=pb($,true)):I;s=$.find("div.fc-event-content");if(s.length)r.contentTop=
s[0].offsetTop}}for(v=0;v<F;v++){r=p[v];if($=r.element){$[0].style.width=Math.max(0,r.outerWidth-r.hsides)+"px";S=Math.max(0,r.outerHeight-r.vsides);$[0].style.height=S+"px";I=r.event;if(r.contentTop!==oa&&S-r.contentTop<10){$.find("div.fc-event-time").text(Y(I.start,u("timeFormat"))+" - "+I.title);$.find("div.fc-event-title").remove()}fa("eventAfterRender",I,I,$)}}}function m(p,s){var v="<",F=p.url,r=Jb(p,u),I=r?" style='"+r+"'":"",L=["fc-event","fc-event-skin","fc-event-vert"];pa(p)&&L.push("fc-event-draggable");
s.isStart&&L.push("fc-corner-top");s.isEnd&&L.push("fc-corner-bottom");L=L.concat(p.className);if(p.source)L=L.concat(p.source.className||[]);v+=F?"a href='"+Qa(p.url)+"'":"div";v+=" class='"+L.join(" ")+"' style='position:absolute;z-index:8;top:"+s.top+"px;left:"+s.left+"px;"+r+"'><div class='fc-event-inner fc-event-skin'"+I+"><div class='fc-event-head fc-event-skin'"+I+"><div class='fc-event-time'>"+Qa(X(p.start,p.end,u("timeFormat")))+"</div></div><div class='fc-event-content'><div class='fc-event-title'>"+
Qa(p.title)+"</div></div><div class='fc-event-bg'></div></div>";if(s.isEnd&&ha(p))v+="<div class='ui-resizable-handle ui-resizable-s'>=</div>";v+="</"+(F?"a":"div")+">";return v}function j(p,s,v){pa(p)&&y(p,s,v.isStart);v.isEnd&&ha(p)&&c(p,s,v);da(p,s)}function t(p,s,v){var F=s.find("div.fc-event-time");pa(p)&&T(p,s,F);v.isEnd&&ha(p)&&R(p,s,F);da(p,s)}function y(p,s,v){function F(){if(!L){s.width(r).height("").draggable("option","grid",null);L=true}}var r,I,L=true,k,D=u("isRTL")?-1:1,Z=V(),ja=O(),
ia=N(),la=ka();s.draggable({zIndex:9,opacity:u("dragOpacity","month"),revertDuration:u("dragRevertDuration"),start:function($,w){fa("eventDragStart",s,p,$,w);i(p,s);r=s.width();Z.start(function(H,S,W,ga){B();if(H){I=false;k=ga*D;if(H.row)if(v){if(L){s.width(ja-10);Eb(s,ia*Math.round((p.end?(p.end-p.start)/wc:u("defaultEventMinutes"))/u("slotMinutes")));s.draggable("option","grid",[ja,1]);L=false}}else I=true;else{E(ba(M(p.start),k),ba(Ua(p),k));F()}I=I||L&&!k}else{F();I=true}s.draggable("option",
"revert",I)},$,"drag")},stop:function($,w){Z.stop();B();fa("eventDragStop",s,p,$,w);if(I){F();s.css("filter","");J(p,s)}else{var H=0;L||(H=Math.round((s.offset().top-U().offset().top)/ia)*u("slotMinutes")+la-(p.start.getHours()*60+p.start.getMinutes()));C(this,p,k,H,L,$,w)}}})}function T(p,s,v){function F(H){var S=xa(M(p.start),H),W;if(p.end)W=xa(M(p.end),H);v.text(X(S,W,u("timeFormat")))}function r(){if(L){v.css("display","");s.draggable("option","grid",[$,w]);L=false}}var I,L=false,k,D,Z,ja=u("isRTL")?
-1:1,ia=V(),la=z(),$=O(),w=N();s.draggable({zIndex:9,scroll:false,grid:[$,w],axis:la==1?"y":false,opacity:u("dragOpacity"),revertDuration:u("dragRevertDuration"),start:function(H,S){fa("eventDragStart",s,p,H,S);i(p,s);I=s.position();D=Z=0;ia.start(function(W,ga,aa,va){s.draggable("option","revert",!W);B();if(W){k=va*ja;if(u("allDaySlot")&&!W.row){if(!L){L=true;v.hide();s.draggable("option","grid",null)}E(ba(M(p.start),k),ba(Ua(p),k))}else r()}},H,"drag")},drag:function(H,S){D=Math.round((S.position.top-
I.top)/w)*u("slotMinutes");if(D!=Z){L||F(D);Z=D}},stop:function(H,S){var W=ia.stop();B();fa("eventDragStop",s,p,H,S);if(W&&(k||D||L))C(this,p,k,L?0:D,L,H,S);else{r();s.css("filter","");s.css(I);F(0);J(p,s)}}})}function R(p,s,v){var F,r,I=N();s.resizable({handles:{s:"div.ui-resizable-s"},grid:I,start:function(L,k){F=r=0;i(p,s);s.css("z-index",9);fa("eventResizeStart",this,p,L,k)},resize:function(L,k){F=Math.round((Math.max(I,s.height())-k.originalSize.height)/I);if(F!=r){v.text(X(p.start,!F&&!p.end?
null:xa(ma(p),u("slotMinutes")*F),u("timeFormat")));r=F}},stop:function(L,k){fa("eventResizeStop",this,p,L,k);if(F)Q(this,p,0,u("slotMinutes")*F,L,k);else{s.css("z-index",8);J(p,s)}}})}var o=this;o.renderEvents=a;o.compileDaySegs=e;o.clearEvents=b;o.slotSegHtml=m;o.bindDaySeg=j;Qb.call(o);var u=o.opt,fa=o.trigger,pa=o.isEventDraggable,ha=o.isEventResizable,ma=o.eventEnd,na=o.reportEvents,ca=o.reportEventClear,da=o.eventElementHandlers,ta=o.setHeight,ua=o.getDaySegmentContainer,qa=o.getSlotSegmentContainer,
V=o.getHoverListener,ea=o.getMaxMinute,ka=o.getMinMinute,ra=o.timePosition,G=o.colContentLeft,q=o.colContentRight,K=o.renderDaySegs,c=o.resizableDayEvent,z=o.getColCnt,O=o.getColWidth,N=o.getSlotHeight,U=o.getBodyContent,ya=o.reportEventElement,J=o.showEvents,i=o.hideEvents,C=o.eventDrop,Q=o.eventResize,E=o.renderDayOverlay,B=o.clearOverlays,n=o.calendar,Y=n.formatDate,X=n.formatDates}function vc(a){var b,e,d,f,g,m;for(b=a.length-1;b>0;b--){f=a[b];for(e=0;e<f.length;e++){g=f[e];for(d=0;d<a[b-1].length;d++){m=
a[b-1][d];if(Cb(g,m))m.forward=Math.max(m.forward||0,(g.forward||0)+1)}}}}function Kb(a,b,e){function d(G,q){G=ra[G];if(typeof G=="object")return $a(G,q||e);return G}function f(G,q){return b.trigger.apply(b,[G,q||da].concat(Array.prototype.slice.call(arguments,2),[da]))}function g(G){return j(G)&&!d("disableDragging")}function m(G){return j(G)&&!d("disableResizing")}function j(G){return Ta(G.editable,(G.source||{}).editable,d("editable"))}function t(G){V={};var q,K=G.length,c;for(q=0;q<K;q++){c=G[q];
if(V[c._id])V[c._id].push(c);else V[c._id]=[c]}}function y(G){return G.end?M(G.end):ta(G)}function T(G,q){ea.push(q);if(ka[G._id])ka[G._id].push(q);else ka[G._id]=[q]}function R(){ea=[];ka={}}function o(G,q){q.click(function(K){if(!q.hasClass("ui-draggable-dragging")&&!q.hasClass("ui-resizable-resizing"))return f("eventClick",this,G,K)}).hover(function(K){f("eventMouseover",this,G,K)},function(K){f("eventMouseout",this,G,K)})}function u(G,q){pa(G,q,"show")}function fa(G,q){pa(G,q,"hide")}function pa(G,
q,K){G=ka[G._id];var c,z=G.length;for(c=0;c<z;c++)if(!q||G[c][0]!=q[0])G[c][K]()}function ha(G,q,K,c,z,O,N){var U=q.allDay,ya=q._id;na(V[ya],K,c,z);f("eventDrop",G,q,K,c,z,function(){na(V[ya],-K,-c,U);qa(ya)},O,N);qa(ya)}function ma(G,q,K,c,z,O){var N=q._id;ca(V[N],K,c);f("eventResize",G,q,K,c,function(){ca(V[N],-K,-c);qa(N)},z,O);qa(N)}function na(G,q,K,c){K=K||0;for(var z,O=G.length,N=0;N<O;N++){z=G[N];if(c!==oa)z.allDay=c;xa(ba(z.start,q,true),K);if(z.end)z.end=xa(ba(z.end,q,true),K);ua(z,ra)}}
function ca(G,q,K){K=K||0;for(var c,z=G.length,O=0;O<z;O++){c=G[O];c.end=xa(ba(y(c),q,true),K);ua(c,ra)}}var da=this;da.element=a;da.calendar=b;da.name=e;da.opt=d;da.trigger=f;da.isEventDraggable=g;da.isEventResizable=m;da.reportEvents=t;da.eventEnd=y;da.reportEventElement=T;da.reportEventClear=R;da.eventElementHandlers=o;da.showEvents=u;da.hideEvents=fa;da.eventDrop=ha;da.eventResize=ma;var ta=da.defaultEventEnd,ua=b.normalizeEvent,qa=b.reportEventChange,V={},ea=[],ka={},ra=b.options}function Qb(){function a(i,
C){var Q=z(),E=qa(),B=V(),n=0,Y,X,p=i.length,s,v;Q[0].innerHTML=e(i);d(i,Q.children());f(i);g(i,Q,C);m(i);j(i);t(i);C=y();for(Q=0;Q<E;Q++){Y=[];for(X=0;X<B;X++)Y[X]=0;for(;n<p&&(s=i[n]).row==Q;){X=Hb(Y.slice(s.startCol,s.endCol));s.top=X;X+=s.outerHeight;for(v=s.startCol;v<s.endCol;v++)Y[v]=X;n++}C[Q].height(Hb(Y))}R(i,T(C))}function b(i,C,Q){var E=l("<div/>"),B=z(),n=i.length,Y;E[0].innerHTML=e(i);E=E.children();B.append(E);d(i,E);m(i);j(i);t(i);R(i,T(y()));E=[];for(B=0;B<n;B++)if(Y=i[B].element){i[B].row===
C&&Y.css("top",Q);E.push(Y[0])}return l(E)}function e(i){var C=fa("isRTL"),Q,E=i.length,B,n,Y,X;Q=ka();var p=Q.left,s=Q.right,v,F,r,I,L,k="";for(Q=0;Q<E;Q++){B=i[Q];n=B.event;X=["fc-event","fc-event-skin","fc-event-hori"];ha(n)&&X.push("fc-event-draggable");if(C){B.isStart&&X.push("fc-corner-right");B.isEnd&&X.push("fc-corner-left");v=q(B.end.getDay()-1);F=q(B.start.getDay());r=B.isEnd?ra(v):p;I=B.isStart?G(F):s}else{B.isStart&&X.push("fc-corner-left");B.isEnd&&X.push("fc-corner-right");v=q(B.start.getDay());
F=q(B.end.getDay()-1);r=B.isStart?ra(v):p;I=B.isEnd?G(F):s}X=X.concat(n.className);if(n.source)X=X.concat(n.source.className||[]);Y=n.url;L=Jb(n,fa);k+=Y?"<a href='"+Qa(Y)+"'":"<div";k+=" class='"+X.join(" ")+"' style='position:absolute;z-index:8;left:"+r+"px;"+L+"'><div class='fc-event-inner fc-event-skin'"+(L?" style='"+L+"'":"")+">";if(!n.allDay&&B.isStart)k+="<span class='fc-event-time'>"+Qa(N(n.start,n.end,fa("timeFormat")))+"</span>";k+="<span class='fc-event-title'>"+Qa(n.title)+"</span></div>";
if(B.isEnd&&ma(n))k+="<div class='ui-resizable-handle ui-resizable-"+(C?"w":"e")+"'>&nbsp;&nbsp;&nbsp;</div>";k+="</"+(Y?"a":"div")+">";B.left=r;B.outerWidth=I-r;B.startCol=v;B.endCol=F+1}return k}function d(i,C){var Q,E=i.length,B,n,Y;for(Q=0;Q<E;Q++){B=i[Q];n=B.event;Y=l(C[Q]);n=pa("eventRender",n,n,Y,u);if(n===false)Y.remove();else{if(n&&n!==true){n=l(n).css({position:"absolute",left:B.left});Y.replaceWith(n);Y=n}B.element=Y}}}function f(i){var C,Q=i.length,E,B;for(C=0;C<Q;C++){E=i[C];(B=E.element)&&
ca(E.event,B)}}function g(i,C,Q){var E,B=i.length,n,Y,X;for(E=0;E<B;E++){n=i[E];if(Y=n.element){X=n.event;if(X._id===Q)O(X,Y,n);else Y[0]._fci=E}}Db(C,i,O)}function m(i){var C,Q=i.length,E,B,n,Y,X={};for(C=0;C<Q;C++){E=i[C];if(B=E.element){n=E.key=Ib(B[0]);Y=X[n];if(Y===oa)Y=X[n]=pb(B,true);E.hsides=Y}}}function j(i){var C,Q=i.length,E,B;for(C=0;C<Q;C++){E=i[C];if(B=E.element)B[0].style.width=Math.max(0,E.outerWidth-E.hsides)+"px"}}function t(i){var C,Q=i.length,E,B,n,Y,X={};for(C=0;C<Q;C++){E=i[C];
if(B=E.element){n=E.key;Y=X[n];if(Y===oa)Y=X[n]=Fb(B);E.outerHeight=B[0].offsetHeight+Y}}}function y(){var i,C=qa(),Q=[];for(i=0;i<C;i++)Q[i]=ea(i).find("td:first div.fc-day-content > div");return Q}function T(i){var C,Q=i.length,E=[];for(C=0;C<Q;C++)E[C]=i[C][0].offsetTop;return E}function R(i,C){var Q,E=i.length,B,n;for(Q=0;Q<E;Q++){B=i[Q];if(n=B.element){n[0].style.top=C[B.row]+(B.top||0)+"px";B=B.event;pa("eventAfterRender",B,B,n)}}}function o(i,C,Q){var E=fa("isRTL"),B=E?"w":"e",n=C.find("div.ui-resizable-"+
B),Y=false;qb(C);C.mousedown(function(X){X.preventDefault()}).click(function(X){if(Y){X.preventDefault();X.stopImmediatePropagation()}});n.mousedown(function(X){function p(ia){pa("eventResizeStop",this,i,ia);l("body").css("cursor","");s.stop();ya();k&&ua(this,i,k,0,ia);setTimeout(function(){Y=false},0)}if(X.which==1){Y=true;var s=u.getHoverListener(),v=qa(),F=V(),r=E?-1:1,I=E?F-1:0,L=C.css("top"),k,D,Z=l.extend({},i),ja=K(i.start);J();l("body").css("cursor",B+"-resize").one("mouseup",p);pa("eventResizeStart",
this,i,X);s.start(function(ia,la){if(ia){var $=Math.max(ja.row,ia.row);ia=ia.col;if(v==1)$=0;if($==ja.row)ia=E?Math.min(ja.col,ia):Math.max(ja.col,ia);k=$*7+ia*r+I-(la.row*7+la.col*r+I);la=ba(na(i),k,true);if(k){Z.end=la;$=D;D=b(c([Z]),Q.row,L);D.find("*").css("cursor",B+"-resize");$&&$.remove();ta(i)}else if(D){da(i);D.remove();D=null}ya();U(i.start,ba(M(la),1))}},X)}})}var u=this;u.renderDaySegs=a;u.resizableDayEvent=o;var fa=u.opt,pa=u.trigger,ha=u.isEventDraggable,ma=u.isEventResizable,na=u.eventEnd,
ca=u.reportEventElement,da=u.showEvents,ta=u.hideEvents,ua=u.eventResize,qa=u.getRowCnt,V=u.getColCnt,ea=u.allDayRow,ka=u.allDayBounds,ra=u.colContentLeft,G=u.colContentRight,q=u.dayOfWeekCol,K=u.dateCell,c=u.compileDaySegs,z=u.getDaySegmentContainer,O=u.bindDaySeg,N=u.calendar.formatDates,U=u.renderDayOverlay,ya=u.clearOverlays,J=u.clearSelection}function Mb(){function a(R,o,u){b();o||(o=j(R,u));t(R,o,u);e(R,o,u)}function b(R){if(T){T=false;y();m("unselect",null,R)}}function e(R,o,u,fa){T=true;m("select",
null,R,o,u,fa)}function d(R){var o=f.cellDate,u=f.cellIsAllDay,fa=f.getHoverListener(),pa=f.reportDayClick;if(R.which==1&&g("selectable")){b(R);var ha;fa.start(function(ma,na){y();if(ma&&u(ma)){ha=[o(na),o(ma)].sort(Gb);t(ha[0],ha[1],true)}else ha=null},R);l(document).one("mouseup",function(ma){fa.stop();if(ha){+ha[0]==+ha[1]&&pa(ha[0],true,ma);e(ha[0],ha[1],true,ma)}})}}var f=this;f.select=a;f.unselect=b;f.reportSelection=e;f.daySelectionMousedown=d;var g=f.opt,m=f.trigger,j=f.defaultSelectionEnd,
t=f.renderSelection,y=f.clearSelection,T=false;g("selectable")&&g("unselectAuto")&&l(document).mousedown(function(R){var o=g("unselectCancel");if(o)if(l(R.target).parents(o).length)return;b(R)})}function Lb(){function a(g,m){var j=f.shift();j||(j=l("<div class='fc-cell-overlay' style='position:absolute;z-index:3'/>"));j[0].parentNode!=m[0]&&j.appendTo(m);d.push(j.css(g).show());return j}function b(){for(var g;g=d.shift();)f.push(g.hide().unbind())}var e=this;e.renderOverlay=a;e.clearOverlays=b;var d=
[],f=[]}function Nb(a){var b=this,e,d;b.build=function(){e=[];d=[];a(e,d)};b.cell=function(f,g){var m=e.length,j=d.length,t,y=-1,T=-1;for(t=0;t<m;t++)if(g>=e[t][0]&&g<e[t][1]){y=t;break}for(t=0;t<j;t++)if(f>=d[t][0]&&f<d[t][1]){T=t;break}return y>=0&&T>=0?{row:y,col:T}:null};b.rect=function(f,g,m,j,t){t=t.offset();return{top:e[f][0]-t.top,left:d[g][0]-t.left,width:d[j][1]-d[g][0],height:e[m][1]-e[f][0]}}}function Ob(a){function b(j){xc(j);j=a.cell(j.pageX,j.pageY);if(!j!=!m||j&&(j.row!=m.row||j.col!=
m.col)){if(j){g||(g=j);f(j,g,j.row-g.row,j.col-g.col)}else f(j,g);m=j}}var e=this,d,f,g,m;e.start=function(j,t,y){f=j;g=m=null;a.build();b(t);d=y||"mousemove";l(document).bind(d,b)};e.stop=function(){l(document).unbind(d,b);return m}}function xc(a){if(a.pageX===oa){a.pageX=a.originalEvent.pageX;a.pageY=a.originalEvent.pageY}}function Pb(a){function b(m){return d[m]=d[m]||a(m)}var e=this,d={},f={},g={};e.left=function(m){return f[m]=f[m]===oa?b(m).position().left:f[m]};e.right=function(m){return g[m]=
g[m]===oa?e.left(m)+b(m).width():g[m]};e.clear=function(){d={};f={};g={}}}var Ya={defaultView:"month",aspectRatio:1.35,header:{left:"title",center:"",right:"today prev,next"},weekends:true,allDayDefault:true,ignoreTimezone:true,lazyFetching:true,startParam:"start",endParam:"end",titleFormat:{month:"MMMM yyyy",week:"MMM d[ yyyy]{ '&#8212;'[ MMM] d yyyy}",day:"dddd, MMM d, yyyy"},columnFormat:{month:"ddd",week:"ddd M/d",day:"dddd M/d"},timeFormat:{"":"h(:mm)t"},isRTL:false,firstDay:0,monthNames:["January",
"February","March","April","May","June","July","August","September","October","November","December"],monthNamesShort:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],dayNames:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],dayNamesShort:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],buttonText:{prev:"&nbsp;&#9668;&nbsp;",next:"&nbsp;&#9658;&nbsp;",prevYear:"&nbsp;&lt;&lt;&nbsp;",nextYear:"&nbsp;&gt;&gt;&nbsp;",today:"today",month:"month",week:"week",
day:"day"},theme:false,buttonIcons:{prev:"circle-triangle-w",next:"circle-triangle-e"},unselectAuto:true,dropAccept:"*"},yc={header:{left:"next,prev today",center:"",right:"title"},buttonText:{prev:"&nbsp;&#9658;&nbsp;",next:"&nbsp;&#9668;&nbsp;",prevYear:"&nbsp;&gt;&gt;&nbsp;",nextYear:"&nbsp;&lt;&lt;&nbsp;"},buttonIcons:{prev:"circle-triangle-e",next:"circle-triangle-w"}},Aa=l.fullCalendar={version:"1.5.4"},Ja=Aa.views={};l.fn.fullCalendar=function(a){if(typeof a=="string"){var b=Array.prototype.slice.call(arguments,
1),e;this.each(function(){var f=l.data(this,"fullCalendar");if(f&&l.isFunction(f[a])){f=f[a].apply(f,b);if(e===oa)e=f;a=="destroy"&&l.removeData(this,"fullCalendar")}});if(e!==oa)return e;return this}var d=a.eventSources||[];delete a.eventSources;if(a.events){d.push(a.events);delete a.events}a=l.extend(true,{},Ya,a.isRTL||a.isRTL===oa&&Ya.isRTL?yc:{},a);this.each(function(f,g){f=l(g);g=new Yb(f,a,d);f.data("fullCalendar",g);g.render()});return this};Aa.sourceNormalizers=[];Aa.sourceFetchers=[];var ac=
{dataType:"json",cache:false},bc=1;Aa.addDays=ba;Aa.cloneDate=M;Aa.parseDate=kb;Aa.parseISO8601=Bb;Aa.parseTime=mb;Aa.formatDate=Oa;Aa.formatDates=jb;var lc=["sun","mon","tue","wed","thu","fri","sat"],Ab=864E5,cc=36E5,wc=6E4,dc={s:function(a){return a.getSeconds()},ss:function(a){return Pa(a.getSeconds())},m:function(a){return a.getMinutes()},mm:function(a){return Pa(a.getMinutes())},h:function(a){return a.getHours()%12||12},hh:function(a){return Pa(a.getHours()%12||12)},H:function(a){return a.getHours()},
HH:function(a){return Pa(a.getHours())},d:function(a){return a.getDate()},dd:function(a){return Pa(a.getDate())},ddd:function(a,b){return b.dayNamesShort[a.getDay()]},dddd:function(a,b){return b.dayNames[a.getDay()]},M:function(a){return a.getMonth()+1},MM:function(a){return Pa(a.getMonth()+1)},MMM:function(a,b){return b.monthNamesShort[a.getMonth()]},MMMM:function(a,b){return b.monthNames[a.getMonth()]},yy:function(a){return(a.getFullYear()+"").substring(2)},yyyy:function(a){return a.getFullYear()},
t:function(a){return a.getHours()<12?"a":"p"},tt:function(a){return a.getHours()<12?"am":"pm"},T:function(a){return a.getHours()<12?"A":"P"},TT:function(a){return a.getHours()<12?"AM":"PM"},u:function(a){return Oa(a,"yyyy-MM-dd'T'HH:mm:ss'Z'")},S:function(a){a=a.getDate();if(a>10&&a<20)return"th";return["st","nd","rd"][a%10-1]||"th"}};Aa.applyAll=ab;Ja.month=mc;Ja.basicWeek=nc;Ja.basicDay=oc;wb({weekMode:"fixed"});Ja.agendaWeek=qc;Ja.agendaDay=rc;wb({allDaySlot:true,allDayText:"all-day",firstHour:6,
slotMinutes:30,defaultEventMinutes:120,axisFormat:"h(:mm)tt",timeFormat:{agenda:"h:mm{ - h:mm}"},dragOpacity:{agenda:0.5},minTime:0,maxTime:24})})(jQuery);
